% Auto-generated by cameraCalibrator app on 16-Jul-2025
%-------------------------------------------------------


% Define images to process
imageFileNames = {'C:\Users\Genhi\Desktop\image7-16\Pic_20250716152547237.jpg',...
    'C:\Users\Genhi\Desktop\image7-16\Pic_20250716152628635.jpg',...
    'C:\Users\Genhi\Desktop\image7-16\Pic_20250716152638583.jpg',...
    'C:\Users\Genhi\Desktop\image7-16\Pic_20250716152653635.jpg',...
    'C:\Users\Genhi\Desktop\image7-16\Pic_20250716152710119.jpg',...
    'C:\Users\Genhi\Desktop\image7-16\Pic_20250716152734483.jpg',...
    'C:\Users\Genhi\Desktop\image7-16\Pic_20250716152744657.jpg',...
    'C:\Users\Genhi\Desktop\image7-16\Pic_20250716152829633.jpg',...
    'C:\Users\Genhi\Desktop\image7-16\Pic_20250716152850967.jpg',...
    'C:\Users\Genhi\Desktop\image7-16\Pic_20250716152900325.jpg',...
    'C:\Users\Genhi\Desktop\image7-16\Pic_20250716152937701.jpg',...
    'C:\Users\Genhi\Desktop\image7-16\Pic_20250716152946539.jpg',...
    'C:\Users\Genhi\Desktop\image7-16\Pic_20250716152957301.jpg',...
    'C:\Users\Genhi\Desktop\image7-16\Pic_20250716153130343.jpg',...
    'C:\Users\Genhi\Desktop\image7-16\Pic_20250716153302928.jpg',...
    'C:\Users\Genhi\Desktop\image7-16\Pic_20250716153355361.jpg',...
    'C:\Users\Genhi\Desktop\image7-16\Pic_20250716153410549.jpg',...
    'C:\Users\Genhi\Desktop\image7-16\Pic_20250716153428461.jpg',...
    'C:\Users\Genhi\Desktop\image7-16\Pic_20250716153452018.jpg',...
    'C:\Users\Genhi\Desktop\image7-16\Pic_20250716153510737.jpg',...
    'C:\Users\Genhi\Desktop\image7-16\Pic_20250716153527359.jpg',...
    'C:\Users\Genhi\Desktop\image7-16\Pic_20250716153543983.jpg',...
    'C:\Users\Genhi\Desktop\image7-16\Pic_20250716153649943.jpg',...
    'C:\Users\Genhi\Desktop\image7-16\Pic_20250716153737098.jpg',...
    'C:\Users\Genhi\Desktop\image7-16\Pic_20250716153909345.jpg',...
    };
% Detect checkerboards in images
[imagePoints, boardSize, imagesUsed] = detectCheckerboardPoints(imageFileNames);
imageFileNames = imageFileNames(imagesUsed);

% Read the first image to obtain image size
originalImage = imread(imageFileNames{1});
[mrows, ncols, ~] = size(originalImage);

% Generate world coordinates of the corners of the squares
squareSize = 6;  % in units of 'millimeters'
worldPoints = generateCheckerboardPoints(boardSize, squareSize);

% Calibrate the camera
[cameraParams, imagesUsed, estimationErrors] = estimateCameraParameters(imagePoints, worldPoints, ...
    'EstimateSkew', false, 'EstimateTangentialDistortion', false, ...
    'NumRadialDistortionCoefficients', 2, 'WorldUnits', 'millimeters', ...
    'InitialIntrinsicMatrix', [], 'InitialRadialDistortion', [], ...
    'ImageSize', [mrows, ncols]);

% View reprojection errors
h1=figure; showReprojectionErrors(cameraParams);

% Visualize pattern locations
h2=figure; showExtrinsics(cameraParams, 'CameraCentric');

% Display parameter estimation errors
displayErrors(estimationErrors, cameraParams);

% For example, you can use the calibration data to remove effects of lens distortion.
undistortedImage = undistortImage(originalImage, cameraParams);

% See additional examples of how to use the calibration data.  At the prompt type:
% showdemo('MeasuringPlanarObjectsExample')
% showdemo('StructureFromMotionExample')
baseDir = 'D:\Git\5DOFGantryArm\lib\data\photos\calibration\';

% 导出相机参数到文件
outputFile = [baseDir, 'camera_params.xml'];
disp(['保存相机参数到: ' outputFile]);

% 创建文件并写入相机参数
fileID = fopen(outputFile, 'w');
fprintf(fileID, '<?xml version="1.0"?>\n');
fprintf(fileID, '<opencv_storage>\n');

% 保存相机矩阵
fprintf(fileID, '<camera_matrix type_id="opencv-matrix">\n');
fprintf(fileID, '  <rows>3</rows>\n');
fprintf(fileID, '  <cols>3</cols>\n');
fprintf(fileID, '  <dt>d</dt>\n');
fprintf(fileID, '  <data>\n    ');
fprintf(fileID, '%.16f %.16f %.16f %.16f %.16f %.16f %.16f %.16f %.16f', ...
    cameraParams.IntrinsicMatrix');
fprintf(fileID, '</data>\n');
fprintf(fileID, '</camera_matrix>\n');

% 保存畸变系数
fprintf(fileID, '<distortion_coefficients type_id="opencv-matrix">\n');
fprintf(fileID, '  <rows>1</rows>\n');
fprintf(fileID, '  <cols>%d</cols>\n', length(cameraParams.RadialDistortion) + length(cameraParams.TangentialDistortion));
fprintf(fileID, '  <dt>d</dt>\n');
fprintf(fileID, '  <data>\n    ');
fprintf(fileID, '%.16f %.16f ', cameraParams.RadialDistortion);
if ~isempty(cameraParams.TangentialDistortion)
    fprintf(fileID, '%.16f %.16f', cameraParams.TangentialDistortion);
end
fprintf(fileID, '</data>\n');
fprintf(fileID, '</distortion_coefficients>\n');

% 保存图像尺寸
fprintf(fileID, '<image_width>%d</image_width>\n', ncols);
fprintf(fileID, '<image_height>%d</image_height>\n', mrows);

% 保存重投影误差 - 使用cameraParams中的MeanReprojectionError
fprintf(fileID, '<reprojection_error>%.16f</reprojection_error>\n', cameraParams.MeanReprojectionError);

fprintf(fileID, '</opencv_storage>\n');
fclose(fileID);



disp('相机参数已成功保存');